version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "idle-prediction"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hczs8kbvvu74"
s3_prefix = "idle-prediction"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
